// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EvilTesterTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void evilTesterTests() {
    driver.get("https://testpages.eviltester.com//");
    driver.findElement(By.cssSelector("#m-pages")).click();
    driver.findElement(By.cssSelector("#m-pagesforms")).click();
    driver.findElement(By.cssSelector("#m-pagesformshtml-form")).click();
    driver.findElement(By.cssSelector("#HTMLFormElements > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > input:nth-child(2)")).sendKeys("jetta101");
    driver.findElement(By.cssSelector("#HTMLFormElements > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1) > input:nth-child(2)")).sendKeys("password123");
    driver.findElement(By.cssSelector("#HTMLFormElements > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(1) > textarea:nth-child(2)")).sendKeys("Hello world!");
    driver.findElement(By.cssSelector("input.styled-click-button:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#m-pagesinput-elements > span")).click();
    driver.findElement(By.linkText("Text Input Elements - Events Display")).click();
    driver.findElement(By.id("text-input")).click();
    driver.findElement(By.id("text-input")).sendKeys("Jambo");
    driver.findElement(By.id("search-input")).click();
    driver.findElement(By.id("search-input")).sendKeys("Entry ");
    driver.findElement(By.cssSelector("#m-pagescss > span")).click();
    driver.findElement(By.cssSelector("#m-pagesforms > span")).click();
    driver.findElement(By.cssSelector("#m-pagesformshtml-form > span")).click();
    assertTrue(driver.findElement(By.cssSelector("tr:nth-child(5) input:nth-child(4)")).isSelected());
    driver.findElement(By.cssSelector("tr:nth-child(5) > td")).click();
    driver.findElement(By.name("checkboxes[]")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) input:nth-child(4)")).click();
    assertFalse(driver.findElement(By.cssSelector("tr:nth-child(5) input:nth-child(4)")).isSelected());
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(6) input:nth-child(3)"));
      assert(elements.size() > 0);
    }
    {
      WebElement dropdown = driver.findElement(By.name("dropdown"));
      dropdown.findElement(By.xpath("//option[. = 'Drop Down Item 2']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(8) option:nth-child(2)")).click();
  }
}
