// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EvilTesterDynamicElementsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void evilTesterDynamicElements() {
    driver.get("https://testpages.eviltester.com/challenges/synchronization/dynamic-buttons-01/");
    driver.findElement(By.id("button00")).click();
    driver.findElement(By.id("button01")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("button01"));
      assert(elements.size() > 0);
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 100);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("button02")));
    }
    driver.findElement(By.id("button02")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("button03")));
    }
    {
      List<WebElement> elements = driver.findElements(By.id("button03"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("button02")).click();
  }
}
