// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    driver.get("https://practicetestautomation.com/practice-test-login/");
    driver.manage().window().setSize(new Dimension(1167, 1032));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("student");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Password123");
    driver.findElement(By.id("submit")).click();
    {
      WebElement element = driver.findElement(By.linkText("Log out"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Log out"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Log out"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.linkText("Log out")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("student1");
    driver.findElement(By.id("password")).sendKeys("Password123");
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("student");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Password1234");
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.id("main-container")).click();
    driver.findElement(By.id("main-container")).click();
  }
}
